/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_grill_placebo_FFmpegManager */

#ifndef _Included_com_grill_placebo_FFmpegManager
#define _Included_com_grill_placebo_FFmpegManager
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jboolean JNICALL Java_com_grill_placebo_FFmpegManager_init
  (JNIEnv *, jobject, jobject, jlong, jobject, jint, jint, jint, jboolean, jboolean, jobject, jint);

JNIEXPORT jlong JNICALL Java_com_grill_placebo_FFmpegManager_decodeFrame
  (JNIEnv *, jobject, jboolean, jint);

JNIEXPORT void JNICALL Java_com_grill_placebo_FFmpegManager_disposeDecoder
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
