/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_grill_placebo_PlaceboManager */

#ifndef _Included_com_grill_placebo_PlaceboManager
#define _Included_com_grill_placebo_PlaceboManager
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_grill_placebo_PlaceboManager
 * Method:    plLogCreate
 * Signature: (IILjava/lang/Object;)J
 */
JNIEXPORT jlong JNICALL Java_com_grill_placebo_PlaceboManager_plLogCreate
  (JNIEnv *, jobject, jint, jint, jobject);

/*
 * Class:     com_grill_placebo_PlaceboManager
 * Method:    plLogDestroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_grill_placebo_PlaceboManager_plLogDestroy
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_grill_placebo_PlaceboManager
 * Method:    plOpenGLCreate
 * Signature: (JJJIII)Z
 */
JNIEXPORT jboolean JNICALL Java_com_grill_placebo_PlaceboManager_plOpenGLCreate
  (JNIEnv *, jobject, jlong, jlong, jlong, jint, jint, jint);

/*
 * Class:     com_grill_placebo_PlaceboManager
 * Method:    plSwapchainResize
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_com_grill_placebo_PlaceboManager_plSwapchainResize
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_grill_placebo_PlaceboManager
 * Method:    renderEGLImage
 * Signature: (JIIII)Z
 */
JNIEXPORT jboolean JNICALL Java_com_grill_placebo_PlaceboManager_renderEGLImage
  (JNIEnv *, jobject, jlong, jint, jint, jint, jint);

/*
 * Class:     com_grill_placebo_PlaceboManager
 * Method:    bindSurfaceToHwDevice
 * Signature: (JLandroid/view/Surface;)V
 */
JNIEXPORT jboolean JNICALL Java_com_grill_placebo_PlaceboManager_bindSurfaceToHwDevice
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     com_grill_placebo_PlaceboManager
 * Method:    plRenderAvFrame
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_grill_placebo_PlaceboManager_plRenderAvFrame
  (JNIEnv *, jobject, jlong);

JNIEXPORT jboolean JNICALL
Java_com_grill_placebo_PlaceboManager_plRenderAvFrameDirect(
    JNIEnv *env, jobject obj,
    jlong avframeHandle);

/*
 * Class:     com_grill_placebo_PlaceboManager
 * Method:    releaseMediaCodecContext
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_grill_placebo_PlaceboManager_releaseMediaCodecContext
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_grill_placebo_PlaceboManager
 * Method:    createMediaCodecHwDevice
 * Signature: (Ljava/lang/Object;)J
 */
JNIEXPORT jlong JNICALL Java_com_grill_placebo_PlaceboManager_createMediaCodecHwDevice
  (JNIEnv *, jclass, jobject);

JNIEXPORT jboolean JNICALL Java_com_grill_placebo_PlaceboManager_assignHwDeviceToCodecContext
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_grill_placebo_PlaceboManager
 * Method:    cleanupResources
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_grill_placebo_PlaceboManager_cleanupResources
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
