/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_grill_consistency_ConsistencyManager */

#ifndef _Included_com_grill_placebo_PlaceboManager
#define _Included_com_grill_placebo_PlaceboManager
#ifdef __cplusplus
extern "C" {
#endif

#include <jni.h>

/* Header for class com_grill_placebo_PlaceboManager */

/*
 * Class:     com_grill_placebo_PlaceboManager
 * Method:    plLogCreate
 * Signature: (IILjava/lang/Object;)J
 */
JNIEXPORT jlong JNICALL Java_com_grill_placebo_PlaceboManager_plLogCreate
  (JNIEnv *, jobject, jint, jint, jobject);

/*
 * Class:     com_grill_placebo_PlaceboManager
 * Method:    plLogDestroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_grill_placebo_PlaceboManager_plLogDestroy
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_grill_placebo_PlaceboManager
 * Method:    createEGLImageFromSurface
 * Signature: (JJLjava/lang/Object;)J
 */
JNIEXPORT jlong JNICALL Java_com_grill_placebo_PlaceboManager_createEGLImageFromSurface
  (JNIEnv *, jobject, jlong, jlong, jobject);

/*
 * Class:     com_grill_placebo_PlaceboManager
 * Method:    plOpenGLCreate
 * Signature: (JJJIII)J
 */
JNIEXPORT jlong JNICALL Java_com_grill_placebo_PlaceboManager_plOpenGLCreate
  (JNIEnv *, jobject, jlong, jlong, jlong, jint, jint, jint);

/*
 * Class:     com_grill_placebo_PlaceboManager
 * Method:    renderEGLImage
 * Signature: (JJIIII)Z
 */
JNIEXPORT jboolean JNICALL Java_com_grill_placebo_PlaceboManager_renderEGLImage
  (JNIEnv *, jobject, jlong, jlong, jint, jint, jint, jint);

/*
 * Class:     com_grill_placebo_PlaceboManager
 * Method:    cleanupResources
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_grill_placebo_PlaceboManager_cleanupResources
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
