name: CI Linux
on:
  workflow_dispatch:

jobs:
  build-binaries-unix:
    name: Build unix lib
    runs-on: ubuntu-latest

    steps:
      - name: Install Java and Git
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-11-jdk git  # Adjust JDK version as needed

      - name: Checkout libplacebo-jni repository
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libavcodec-dev libavformat-dev libegl1-mesa-dev libsdl2-dev libxxhash-dev glslang-dev libvulkan-dev liblcms2-dev cmake

      - name: Install Meson and Ninja
        run: |
          sudo apt-get install -y python3-pip
          pip3 install --upgrade meson==1.3.0
          pip3 install --upgrade ninja==1.11.1

      - name: Build libplacebo
        working-directory: ./libplacebo-jni-native/3rdparty/libplacebo
        run: |
          meson setup build --buildtype release --default-library=static -Ddemos=false -Dprefix=$PWD/install
          meson compile -vC build
          meson install -C build

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build libplacebo-jni-java compile java
        run: |
          ./gradlew clean
          ./gradlew libplacebo-jni-java:compileJava

      - name: Configure and Build libplacebo-jni with CMake
        run: |
          cmake -G "Ninja" -B build -S ./libplacebo-jni-native \
            -DCMAKE_BUILD_TYPE=Release \
            -DLIBPLACEBO_LIB_PATH=${{ github.workspace }}/libplacebo-jni-native/3rdparty/libplacebo/install/lib/x86_64-linux-gnu/libplacebo.a \
            -DCMAKE_RUNTIME_OUTPUT_DIRECTORY=${{ github.workspace }}/build/nativeBinaries \
            -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=${{ github.workspace }}/build/nativeBinaries \
            -DCMAKE_ARCHIVE_OUTPUT_DIRECTORY=${{ github.workspace }}/build/nativeBinaries \
            -DGENERATED_JNI_HEADERS_DIR=${{ github.workspace }}/build/generatedHeaders \
            -DIS_RUNNING_ON_WINDOWS=OFF
          cmake --build build

      - name: Rename DLL file
        run: mv ${{github.workspace}}/build/nativeBinaries/libplacebo-jni-native.so ${{github.workspace}}/build/nativeBinaries/libplacebo-jni-native-64.so

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-libplacebo-jni-artifact-64bit
          path: ${{github.workspace}}/build/nativeBinaries/libplacebo-jni-native-64.so
