name: CI Linux
on:
  workflow_dispatch:
    inputs:
      build_glslang:
        description: 'Build glslang (true/false)'
        required: true
        default: 'true' # to save time, actual build is already in libs folder

jobs:
  build-binaries-unix:
    name: Build unix lib
    runs-on: ubuntu-latest
    env:
      BUILD_GLSLANG: ${{ github.event.inputs.build_glslang }}

    steps:
      - name: Checkout libplacebo-jni repository
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Checkout glslang repository
        if: env.BUILD_GLSLANG == 'true'
        uses: actions/checkout@v2
        with:
          repository: 'KhronosGroup/glslang'
          path: 'glslang'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libavcodec-dev libavformat-dev libegl1-mesa-dev libsdl2-dev libxxhash-dev glslang-dev libvulkan-dev liblcms2-dev cmake

      - name: Install Meson and Ninja
        run: |
          sudo apt-get install -y python3-pip
          pip3 install --upgrade meson==1.3.0
          pip3 install --upgrade ninja==1.11.1

      - name: Update glslang sources
        if: env.BUILD_GLSLANG == 'true'
        working-directory: ./glslang
        run: ./update_glslang_sources.py

      - name: Build glslang
        if: env.BUILD_GLSLANG == 'true'
        working-directory: ./glslang
        run: |
          cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -DCMAKE_INSTALL_PREFIX="$(pwd)/install" .
          cmake --build . --config Release --target install

      - name: Upload gslang artefacts
        if: env.BUILD_GLSLANG == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: gslang-artefacts-x64
          path: ${{github.workspace}}/glslang/install

      - name: Build libplacebo
        working-directory: ./libplacebo-jni-native/3rdparty/libplacebo
        run: |
          meson setup build --buildtype release --default-library=static -Ddemos=false -Dprefix=$PWD/install
          meson compile -vC build
          meson install -C build

      - name: Upload libplacebo artefacts
        uses: actions/upload-artifact@v4
        with:
          name: libplacebo-artefacts-${{ matrix.arch }}
          path: ${{github.workspace}}/libplacebo-jni-native/3rdparty/libplacebo/install

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build libplacebo-jni-java compile java
        run: |
          ./gradlew clean
          ./gradlew libplacebo-jni-java:compileJava

      - name: Configure and Build libplacebo-jni with CMake
        run: |
          if [ "${{ env.BUILD_GLSLANG }}" = "true" ]; then
            GLSLANG_LIBS_DIR=${{github.workspace}}/glslang/install/lib
            GLSLANG_HEADERS_DIR="${{github.workspace}}/glslang/install/include
          else
            GLSLANG_LIBS_DIR=${{github.workspace}}/libs/glslang/linux/x64/lib
            GLSLANG_HEADERS_DIR=${{github.workspace}}/libs/glslang/linux/x64/include
          fi
          
          cmake -G "Ninja" -B build -S ./libplacebo-jni-native \
            -DCMAKE_BUILD_TYPE=Release \
            -DLIBPLACEBO_LIB_PATH=${{ github.workspace }}/libplacebo-jni-native/3rdparty/libplacebo/install/lib/x86_64-linux-gnu/libplacebo.a \
            -DCMAKE_RUNTIME_OUTPUT_DIRECTORY=${{ github.workspace }}/build/nativeBinaries \
            -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=${{ github.workspace }}/build/nativeBinaries \
            -DCMAKE_ARCHIVE_OUTPUT_DIRECTORY=${{ github.workspace }}/build/nativeBinaries \
            -DGENERATED_JNI_HEADERS_DIR=${{ github.workspace }}/build/generatedHeaders \
            -DGLSLANG_LIBS_DIR=${GLSLANG_LIBS_DIR} \
            -DGLSLANG_HEADERS_DIR=${GLSLANG_HEADERS_DIR}
            -DIS_RUNNING_ON_WINDOWS=OFF
          cmake --build build

      - name: Rename DLL file
        run: mv ${{github.workspace}}/build/nativeBinaries/libplacebo-jni-native.so ${{github.workspace}}/build/nativeBinaries/libplacebo-jni-native-64.so

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-libplacebo-jni-artifact-64bit
          path: ${{github.workspace}}/build/nativeBinaries/libplacebo-jni-native-64.so
