name: CI Linux
on:
  workflow_dispatch:
    inputs:
      build_glslang:
        description: 'Build glslang (true/false)'
        required: true
        default: 'false' # to save time, actual build is already in libs folder
      build_libplacebo:
        description: 'Build libplacebo (true/false)'
        required: true
        default: 'false' # to save time, actual build is already in libs folder
      build_shaderc:
        description: 'Build shaderc (true/false)'
        required: true
        default: 'false' # not needed
      build_vulkan-loader:
        description: 'Build vulkan-loader (true/false)'
        required: true
        default: 'false' # not needed
      build_lcms2:
        description: 'Build lcms2 (true/false)'
        required: true
        default: 'false' # not needed

jobs:
  build-binaries-unix:
    name: Build unix lib
    runs-on: ubuntu-latest
    env:
      BUILD_GLSLANG: ${{ github.event.inputs.build_glslang }}
      BUILD_LIBPLACEBO: ${{ github.event.inputs.build_libplacebo }}
      BUILD_SHADERC: ${{ github.event.inputs.build_shaderc }}
      BUILD_VULKAN_LOADER: ${{ github.event.inputs.build_vulkan }}
      BUILD_LCMS2: ${{ github.event.inputs.build_lcms2 }}

    steps:
      - name: Checkout libplacebo-jni repository
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Checkout Nuklear library
        uses: actions/checkout@v2
        with:
          repository: 'Immediate-Mode-UI/Nuklear'
          path: 'Nuklear'
          ref: '4.10.7'

      - name: Checkout shaderc repository
        if: env.BUILD_SHADERC == 'true'
        uses: actions/checkout@v2
        with:
          repository: 'google/shaderc'
          path: 'shaderc'
          ref: 'v2023.7'

      - name: Checkout glslang repository
        if: env.BUILD_GLSLANG == 'true'
        uses: actions/checkout@v2
        with:
          repository: 'KhronosGroup/glslang'
          path: 'glslang'

      - name: Checkout vulkan-loader repository
        if: env.BUILD_VULKAN_LOADER == 'true'
        uses: actions/checkout@v2
        with:
          repository: 'KhronosGroup/Vulkan-Loader'
          path: 'vulkan-loader'

      - name: Checkout Little-CMS repository
        if: env.BUILD_LCMS2 == 'true'
        uses: actions/checkout@v2
        with:
          repository: 'mm2/Little-CMS'
          path: 'Little-CMS'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libavcodec-dev libavformat-dev libegl1-mesa-dev libsdl2-dev libxxhash-dev glslang-dev libvulkan-dev liblcms2-dev build-essential libx11-xcb-dev libxkbcommon-dev libwayland-dev libxrandr-dev cmake

      - name: Install xbxc dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libxcb1-dev libxcb-randr0-dev libxcb-keysyms1-dev libxcb-icccm4-dev libxcb-image0-dev libxcb-xkb-dev

      - name: Install Meson and Ninja
        run: |
          sudo apt-get install -y python3-pip
          pip3 install --upgrade meson==1.3.0
          pip3 install --upgrade ninja==1.11.1

      - name: Build Little-CMS
        if: env.BUILD_LCMS2 == 'true'
        working-directory: ./Little-CMS
        run: |
          meson setup build --buildtype release --default-library=static
          meson compile -C build
          meson install -C build

      - name: Upload Little-CMS
        if: env.BUILD_LCMS2 == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: lcms2-linux-x64bit
          path: ${{github.workspace}}/Little-CMS

      - name: Build shaderc
        if: env.BUILD_SHADERC == 'true'
        working-directory: ./shaderc
        run: |
          ./utils/git-sync-deps
          mkdir -p build
          cd build
          cmake -DSHADERC_SKIP_TESTS=ON ..
          cmake --build . --config Release

      - name: Upload shaderc artefacts
        if: env.BUILD_SHADERC == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: shaderc-artefacts-${{ matrix.arch }}
          path: ${{github.workspace}}/shaderc

      - name: Build vulkan-loader
        if: env.BUILD_VULKAN_LOADER == 'true'
        working-directory: ./vulkan-loader
        run: |
          cmake -S . -B build -D UPDATE_DEPS=On
          cmake --build build --config Release

      - name: Upload vulkan-loader artefacts
        if: env.BUILD_VULKAN_LOADER == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: vulkan-loader-artefacts-x64
          path: ${{github.workspace}}/vulkan-loader

      - name: Update glslang sources
        if: env.BUILD_GLSLANG == 'true'
        working-directory: ./glslang
        run: ./update_glslang_sources.py

      - name: Build glslang
        if: env.BUILD_GLSLANG == 'true'
        working-directory: ./glslang
        run: |
          cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -DCMAKE_INSTALL_PREFIX="$(pwd)/install" .
          cmake --build . --config Release --target install

      - name: Upload gslang artefacts
        if: env.BUILD_GLSLANG == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: gslang-artefacts-x64
          path: ${{github.workspace}}/glslang/install

      - name: Apply fix_p010_rendering patch to libplacebo
        #if: env.BUILD_LIBPLACEBO == 'true'
        working-directory: ./libplacebo-jni-native/3rdparty/libplacebo
        run: |
          git apply ../fix_p010_rendering.patch

      - name: Build libplacebo
        #if: env.BUILD_LIBPLACEBO == 'true'
        working-directory: ./libplacebo-jni-native/3rdparty/libplacebo
        run: |
          meson setup build --buildtype release --default-library=static -Ddemos=false -Dprefix=$PWD/install
          meson compile -vC build
          meson install -C build

      - name: Upload libplacebo artefacts
        #if: env.BUILD_LIBPLACEBO == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: libplacebo-artefacts-x64
          path: ${{github.workspace}}/libplacebo-jni-native/3rdparty/libplacebo/install

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Install jq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Build libplacebo-jni-java compile java
        run: |
          ./gradlew clean
          ./gradlew libplacebo-jni-java:compileJava

      - name: Configure and Build libplacebo-jni with CMake
        run: |
          if [ "${{ env.BUILD_GLSLANG }}" = "true" ]; then
            GLSLANG_LIBS_DIR=${{github.workspace}}/glslang/install/lib
            GLSLANG_HEADERS_DIR=${{github.workspace}}/glslang/install/include
          else
            GLSLANG_LIBS_DIR=${{github.workspace}}/libs/glslang/linux/x64/lib
            GLSLANG_HEADERS_DIR=${{github.workspace}}/libs/glslang/linux/x64/include
          fi
          
          LIBPLACEBO_LIB_PATH=${{github.workspace}}/libplacebo-jni-native/3rdparty/libplacebo/install/lib/libplacebo.a
          LIBPLACEBO_HEADERS_DIR=${{github.workspace}}/libplacebo-jni-native/3rdparty/libplacebo/install/include
          
          cmake -G "Ninja" -B build -S ./libplacebo-jni-native \
            -DCMAKE_BUILD_TYPE=Release \
            -DVULKAN_LIB_DIR=${{github.workspace}}/libs/vulkan-loader/linux/x64 \
            -DLIBPLACEBO_LIB_PATH=${LIBPLACEBO_LIB_PATH} \
            -DLIBPLACEBO_HEADERS_DIR=${LIBPLACEBO_HEADERS_DIR} \
            -DCMAKE_RUNTIME_OUTPUT_DIRECTORY=${{ github.workspace }}/build/nativeBinaries \
            -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=${{ github.workspace }}/build/nativeBinaries \
            -DCMAKE_ARCHIVE_OUTPUT_DIRECTORY=${{ github.workspace }}/build/nativeBinaries \
            -DGENERATED_JNI_HEADERS_DIR=${{ github.workspace }}/build/generatedHeaders \
            -DGLSLANG_LIBS_DIR=${GLSLANG_LIBS_DIR} \
            -DGLSLANG_HEADERS_DIR=${GLSLANG_HEADERS_DIR} \
            -DSHADERC_LIB_DIR=${{github.workspace}}/libs/shaderc/linux/x64/lib \
            -DSHADERC_HEADERS_DIR=${{github.workspace}}/libs/shaderc/linux/x64/include \
            -DFFMPEG_DIR=${{github.workspace}}/libs/ffmpeg/linux/x64 \
            -DLCMS2_DIR=${{github.workspace}}/libs/lcms2/linux/x64 \
            -DNUKLEAR_DIR=${{github.workspace}}/Nuklear \
            -DVKMEMALLOC_HEADERS=${{github.workspace}}/libs/vulkan-memory-allocator/include \
            -DIS_RUNNING_ON_WINDOWS=OFF
          cmake --build build
        shell: bash

      - name: Rename DLL file
        run: mv ${{github.workspace}}/build/nativeBinaries/libplacebo-jni-native.so ${{github.workspace}}/build/nativeBinaries/libplacebo-jni-native-64.so

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-libplacebo-jni-artifact-64bit
          path: ${{github.workspace}}/build/nativeBinaries/libplacebo-jni-native-64.so
